### PR TITLE
Py39 updates

### LINKED ISSUE #320: Python 3.9
Following #313 we will have the product of python 3.6 3.7 3.8 x stable,dev environments under test with travis ci.  Currently some packages are not available for python 3.9 which was just released.  Instead of working around that temporarily, I think we can just wait to re-evaluate and add these lines at a later date.

```
    # Some 3.9 depends are not yet avail, 11/06/2020.
    # - python: 3.9
    #   env:
    #     - TOXENV=py39-stable
    #     - TOXENV=py39-dev
```

### PR DESCRIPTION
**Pull request by garrettwrong**
Potential updates to support Python 3.9 and update some of our numerical packages.

We're still dependent on PyFFTW to either make a 3.9 wheel, or fix their packaging so we can pip install from source.  It is possible for us to work around that if it becomes essential.  I reported the issue to them, and I think their developers are looking into it. They have seen it a few times now... so I suggest we wait before we workaround in our packaging.

Closes #320

### CODE REVIEW

**Comment by garrettwrong** [comment]
Adding some notes.

 Numpy, >=1.20 does not support Python 3.6.  This has the tandem effect of limiting scipy versions, and anything that might require these two, and so on.
https://numpy.org/doc/stable/release/1.20.0-notes.html

skimage is removed per #388 . That helps.

pyfftw now has a PR which migrates to new python packaging format, along with some packaging depend changes.  I hope that will install the required cython that pip needs to build from source. Eventually they will also make a 3.9 wheel.  This leads to the last issue I encountered... there is some potential for compatibility issues between older numpy with newer pyfftw and vice versa. It looks something like below.  This was latest pyfftw with numpy 1.19.  Goes away with numpy 1.20.  Will need to check that out again when they've moved...

```
  E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by garrettwrong** [comment]
Noting that PyFFTW has recently merged their `pyproject.toml` patch which should cover some of the issues with 3.9.  However this is still waiting on cross platform 3.9 wheels or a new release which includes the previously mentioned patch.

**Comment by garrettwrong** [comment]
Checking up on this, still waiting on PyFFTW to support 3.9.  Maybe our next release (they don't release too often).

The changes/conflicts here are relatively minor, nothing to worry about.

**Comment by garrettwrong** [comment]
Planning to discuss this today, but I think because this PR is sufficiently conlficted/stale (and is easier to just redo) I will move to close this PR and start a fresh one following some discussion.  Today I can split this into three topics, the bulk 3.9 support changes (int, float replacements), package version changes, and the pyfftw which was being discussed by their maintainers yesterday...

**Comment by janden** [comment]
Makes sense to me.

**Pull request closed without merging**
