### PR TITLE
Add Python 3.12, drop 3.8

### PR DESCRIPTION
**Pull request by garrettwrong**
Moves default Python to 3.9 in docs and environments.

### CODE REVIEW

**Comment by garrettwrong** [comment]
Kicking off the additional CI platforms

**Comment by garrettwrong** [comment]
This is "waiting on 3.8" because I will need to adjust the CI requirements to drop 3.8.

**Comment by garrettwrong** [comment]
@j-c-c , can I get a review, thanks.

**Review by j-c-c — APPROVED** [review]
Hey, looks good. Sorry for the delay!

**Pull request merged**
