### PR TITLE
Fix two benign res warnings

### PR DESCRIPTION
**Pull request by garrettwrong**
Found two places still using Image.res ( one string and one gallery example).

### CODE REVIEW

**Comment by garrettwrong** [comment]
This PR, like any other current ones, needs the scipy patch from #826 to pass CI.

**Review by j-c-c — APPROVED** [review]
Nice catch. Should we be removing the `Image.res` property altogether? Maybe I missed the discussion on this.

**Comment by garrettwrong** [comment]
> Nice catch. Should we be removing the `Image.res` property altogether? Maybe I missed the discussion on this.

In a later release.  I'm trying to do it this way with the warnings in order to break less things if anyone happens to be using `.res`. This is written in the message/code.

**Comment by garrettwrong** [comment]
Merging

**Pull request merged**
