### PR TITLE
ctf estimate fix

### PR DESCRIPTION
**Pull request by garrettwrong**
This reverts some of the incomplete changes in `v0.10.1`'s `develop` and solidifies the unit test reference.

The unit test for defocus u, v are enabled and set to be within 5% of CTFFIND4 for the test micrograph using the pixel size 1.77 listed on EMPIAR.  (Thanks @chris-langfield !)

The angle still appears to be incorrect, and I have not been able to get an angle that made sense to me from the original `ctf` branch either... so we'll need to tackle that next.

### CODE REVIEW

**Comment by garrettwrong** [comment]
#742

**Review by chris-langfield — APPROVED** [review]
Cool this is definitely a step forward. Thanks Garrett

**Review by j-c-c — APPROVED** [review]
Looks good!

**Comment by garrettwrong** [comment]
Great. Merging.

**Pull request merged**
