### PR TITLE
Add CLICK command for orientation estimation

### PR DESCRIPTION
**Pull request by junchaoxia**
Closing issue #336.

### CODE REVIEW

**Comment by janden** [comment]
Issue #336 concerns adding a click command for orientation estimation. This PR does that, plus adds a new type of image source that is unable to provide images. Can you briefly explain why this is necessary?

**Comment by junchaoxia** [comment]
@janden The major reason is that we tend to make the ImageSource class immutable. The new image source is developed in the similar way for the DenoisedImageSource class in 
  https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/master/src/aspire/denoising/denoised_src.py.  
Over there we tend to generate a new source object for denoised images instead of replacing the images in the old one. Here we want to save the rotation matrices into a new source object but the images are not changes and no need to save again. That is the reason for  not implementing the `_images` function. In order to access the images, we can use the original ImageSource. Of couse we can also implement  `_images` to call `images()` from the src object form the original ImageSource.

**Comment by janden** [comment]
All right, but then why don't we implement this as a flag to the save function to just tell it to save the metadata and let it refer to an existing file? Maybe it would make sense to have the ImageSource have two methods: `save_metadata` and `save_images`. Then the higher-level `save` method could do both. At any rate, this PR is not the place to be making these larger changes.

**Comment by junchaoxia** [comment]
There is an old issue #141 discussing the unified star file. I think it is related to the problem here. The `save` function in the `ImageSource` class  call `star_star` function which saves the star file for metadata and mrc files for images at the same time. It is good to re-implement it as two parts, `save_metadata` and `save_images`. I tried to separate it in a similar way previously but did not follow.  I will add the notation in issue #141 to follow in separate PRs.

**Comment by janden** [comment]
I don't quite follow what's going on in that issue. From what I remember, we wanted to have `save_metadata`, which returned a list of generated image filenames and image indices. This would then be provided as an argument to `save_images`. If it is not provided, the filenames and indices in the source will be used. This should be implemented in the superclass `ImageSource` so the behavior is the same for all sources.

The other thing we discussed was to separate out `OrientEstimationSource` into a separate PR. We should close this PR or turn it into a draft until these other issues are resolved.

**Comment by junchaoxia** [comment]
In PR #368, I tried to address the problem of `save_metadata` and `save_images` in the base ImageSource class.  When that is formalized we can apply to other classes. I think we should close this one.

**Comment by junchaoxia** [comment]
@janden The `save` function was updated to use the new implemented `save_metadata` for saving STAR file only.

**Comment by junchaoxia** [comment]
@janden The `save` function was updated to use the new implemented `save_metadata` for saving STAR file only.

**Review by janden — APPROVED** [review]

**Review by garrettwrong — APPROVED** [review]
I checked this out locally and made sure it will pass the tox checks (since Travis was disabled during the time this was pushed).

**Pull request merged**
