### PR TITLE
`develop` ~~> `main` v0.12.1

### PR DESCRIPTION
**Pull request by garrettwrong**
Drafting release notes below.  Still need to run the integration tests.

----------------------------

ASPIRE v0.12.1 is bugfix release, adding a mix of new features and cleanup.

This release provides the following features:

* Interoperable 2D basis (covar2d, class averaging)
* Improved Relion interoperability
* Common Line SDP method
* Shared 2D Basis tests
* Common Lines optional fuzzy mask
* Add `Coef` class
* Nearest rotation (SVD) util method
* FRC and FSC plotting option (disable cutoff)

Bug fixes:

* Enforce grid conventions
* FLE expand unit test convergence
* Sync voting unit test patch
* Whitening extremal value patch
* Adds improved image projection tests
* Adds improved volume rotation tests
* FBBasis3D NaN values for large resolution
* {F}PSWF basis float32 patch
* Extend `eval_coords` to many volumes
* Enforce block dtypes on assignment
* Reduce package import resource util

Systems/CI Updates:

* Flake8 Style Updates
* Add public Issue template
* Docstring cleanup
* Adds docstring linting util to CI
* Additional `pytest` conversions
* Removes `parameterized_class`
* Workaround Ray/pydantic dependency conflict

Documentation:

* Adds Relion interoperability gallery
* Adds Weighted spectral volume gallery
* Update public facing Code of Conduct
* Add K2 camera note to CTF estimator module
* Removes deprecated legacy example scripts

### CODE REVIEW

**Review by j-c-c — APPROVED** [review]
🚀

**Comment by garrettwrong** [comment]
Integration tests look similar to last release.  Testing 10073 with higher reolutions to get an idea what FSC resolution it is achieving as a baseline.

**Review by janden — APPROVED** [review]
Looks good. Except the release notes should say “bugfix release”, not “minor release”.

**Comment by garrettwrong** [comment]
> Looks good. Except the release notes should say “bugfix release”, not “minor release”.

RIght, fixed. Thanks.

**Pull request merged**
