### PR TITLE
Importlib unhack

### PR DESCRIPTION
**Pull request by garrettwrong**
This top level import (which I put in a long time ago for potential convenience) seems to be causing increased memory usage.

I don't think anyone uses the feature. Its also most of what makes the first import of `aspire` slow.

Tentatively suggesting we remove it.  Running some large experiments now to see if improves the resource utilization.

### CODE REVIEW

**Comment by garrettwrong** [comment]
Updating with the dynamic importing compromise suggested by Joakim(numpy).

The `getattr` wrapper is now dynamically performing the `importlib` I was doing before at the top level.

This keeps the ability to do the following:

```
import aspire
s = aspire.source.Simulation()
```

**Comment by garrettwrong** [comment]
@j-c-c Can you do a prelim review on this? I'm still running the tests regarding the resource usage, but I think we want this either way at this point.  (I know its already improving some resource usage cases and has the best compromise regarding imports).

**Review by j-c-c — DISMISSED** [review]
This looks good to me. Everything seems to work as expected.

The only thing I would change (which is not functionally important) is adding backticks around `{__name__}` and `{attr}` in the error message.

**Comment by garrettwrong** [comment]
> This looks good to me. Everything seems to work as expected.
> 
> The only thing I would change (which is not functionally important) is adding backticks around `{__name__}` and `{attr}` in the error message.

Sure, done.

**Review by j-c-c — APPROVED** [review]

**Comment by garrettwrong** [comment]
Merging.

**Pull request merged**
