### PR TITLE
Add sphinx to Travis installs

### LINKED ISSUE #359: Fix GH Pages doc deployment
Looks like the latest master is not able to find the sphinx package during the deployment stage on Travis.  As it is written, this stage happens only for master, after all the testing that is done in develop. I believe this is the first time this stage has been run since May, and with all the changes I'm not surprised it didn't work the first time.

Documentation building is actually tested during development, but that is within the tox environment which we've controlled, not outside (ie on Travis directly which is how the `deploy` is coded). I think this happened because I moved us away from using Conda in travis, since conda was already covered in azure tests. I think I just need to add a sphinx install to travis.

### PR DESCRIPTION
**Pull request by garrettwrong**
Closes #359 , hopefully restoring the automatic doc generation Vineet setup for us a while back.

### CODE REVIEW

**Comment by janden** [comment]
Wouldn't it make more sense to add this to `install_requires`? (That's where `sphinxcontrib-bibtex` and co live.)

**Comment by garrettwrong** [comment]
I am not actually installing aspire on Travis directly anymore (that is actually the root of the issue).  `pip install aspire` will already install sphinx... no need to add to setup.py, though I guess we could call it out.

Instead of the direct install, the CI tests is done inside tox virtual envs.  

 Im not 100% on this change resolving, maybe 90%, ... but I didn't really design this setup, just trying to work with it... As it is written it is sort of hard to iteratively test it.

**Comment by garrettwrong** [comment]
Now that Travis is defunct (we're out of time for the month on day 0), this isn't going to kick off anyway.

I'd still put this change in... and I can roll out the 0.6.2 package, then try to manually push the latest docs.

**Comment by janden** [comment]
That's funny…

Yeah let's do that, then.

**Review by janden — APPROVED** [review]

**Pull request merged**
