### PR TITLE
Fix pytest

### LINKED ISSUE #224: pytest should just work
We shouldn't have to specify `pytest dirname` except as a filter.  That is, most people just expect to call `pytest` and things work. 
 We do this filter because some of our code breaks on test collection.  We should fix our code, but in the mean time we can control this with a config file so the commonly used command works.

I'll try to put something together for this shortly. I'm tired of hitting it myself and hearing other people hit it.

### PR DESCRIPTION
**Pull request by garrettwrong**
Closes #224 

This should hold us over until we fix offending code (clearly we punted way too long...).

Stops the following from coming up when a developer tries to run the `pytest` command as it was intended:

```
(aspire_foo_master) ➜  ASPIRE-Python.dev git:(develop) pytest              
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.6.10, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/garrett/Dropbox/PU/aspire/ASPIRE-Python.dev, configfile: pytest.ini
plugins: cov-2.10.0
collected 178 items / 1 error / 1 deselected / 176 selected                                                                                                             

================================================================================ ERRORS =================================================================================
________________________________________________ ERROR collecting src/aspire/aspire/em_classavg/test_forward_backward.py ________________________________________________
ImportError while importing test module '/home/garrett/Dropbox/PU/aspire/ASPIRE-Python.dev/src/aspire/aspire/em_classavg/test_forward_backward.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../anaconda3/envs/aspire_foo_master/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
src/aspire/aspire/em_classavg/test_forward_backward.py:1: in <module>
    import data_utils
E   ModuleNotFoundError: No module named 'data_utils'
======================================================================== short test summary info ========================================================================
ERROR src/aspire/aspire/em_classavg/test_forward_backward.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================== 1 deselected, 1 error in 1.15s =====================================================================
```

### CODE REVIEW

**Review by janden — APPROVED** [review]
Looks good. Can we add an issue about cleaning up that particular file so we don't forget it (now that it's not popping up every other day when we run `pytest`)?

**Comment by garrettwrong** [comment]
Sure I dropped the same log in an issue. (I just caught another osx CI failure here, will make an issue with that log. The fact a package hash doesn't match makes me think it is a layer underneath us, but I'd have to look how to refresh things.)

**Comment by janden** [comment]
:pray:

**Review by junchaoxia — APPROVED** [review]
I think "pytest tests" was used previously. Just be ware that the whole folder of src/apire/aspire is from the original Python code and only PSWF basis and orientation estimation parts were extracted to the new framework.

**Pull request merged**
