### PR TITLE
Polar Fourier - Row Major (662)

### LINKED ISSUE #662: Change Polar Fourier to Row Major
In `src/aspire/abinitio/commonline_base.py` the polar Fourier `self.pf` is transposed into column major order here:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/abinitio/commonline_base.py#L69-L70

then later converted back to row major order when performing a correlation:
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/1bff8d3884183203bd77695a76bccb1efc909fd3/src/aspire/abinitio/commonline_base.py#L161-L162

We should consider keeping this in row major form.

### PR DESCRIPTION
**Pull request by j-c-c**
This PR changes the polar Fourier transform to row major. It was formally in column major order, presumably to match the MATLAB code, but was converted to row major whenever used. 

This closes #662.

### CODE REVIEW

**Review by garrettwrong — APPROVED** [review]
LGTM thanks! Two questions. Did you put eyes on a reconstruction using this update yet? Second, did you notice any performance change (unit test or recon)?

**Comment by j-c-c** [comment]
> LGTM thanks! Two questions. Did you put eyes on a reconstruction using this update yet? Second, did you notice any performance change (unit test or recon)?

I did not put eyes on a reconstruction. I'll run one now and confirm nothing has changed. As for performance, timing is basically unchanged for both `test_orient_sync.py` and `test_orient_symmetric.py` unit tests. I'll report if there's any performance change for the reconstruction.

**Comment by j-c-c** [comment]
@garrettwrong, I ran the pipeline demo with column major and row major versions. Performance is unchanged. More specifically, the mse on the estimated rotations is the same in both cases and timings were the same. Also, the reconstructions look identical to the eye.

**Comment by garrettwrong** [comment]
Awesome, thanks! Approved.

**Pull request merged**
