### PR TITLE
Toxit black

### PR DESCRIPTION
**Pull request by garrettwrong**
Implements black formatting and begins some migration of existing tasks to tox.  Also implements several new checks.

Fixes virtually all pep8 compliance issues, excluding too long comments/docs.

Also documents reformatting commit s.t. it can be ignored by git blame.

### CODE REVIEW

**Comment by garrettwrong** [comment]
Closes #220 (mostly, I will break out the docstring style/linting into it's own issue later).

**Comment by garrettwrong** [comment]
For reviewing this, it might be more prudent to go through the commits (in consideration of the bulk autoformatting line changes).

**Comment by garrettwrong** [comment]
I've updated the developer document a little to reflect these changes being merged in, and also include some syntax examples for their use. Probably during a dev meeting I can demo or something as well.

**Review by janden — APPROVED** [review]
LGTM. Would be good to do a run-through at the next dev meeting.

**Comment by garrettwrong** [comment]
Yep, I will be able to demonstrate some of the commands in our team meeting.

@junchaoxia , this change set is going in. It is going to make the travis CI testing procedure stricter in a few ways.  I have added some notes to the developer google doc.

**Pull request merged**
