### PR TITLE
Change `self.L` and `self.n` to `self.src.L` and `self.src.n` for estimators

### LINKED ISSUE #531: `Estimator.L` can be `Estimator.src.L`
Followup to the discussion on #517

The `Estimator` class derives its `L` property directly from the `Source` from which it is instantiated. 

https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/3223d6c2c308af66f321ca2b0ddf3933045f904b/src/aspire/reconstruction/estimator.py#L24

Similarly `NoiseEstimator` https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/master/src/aspire/noise/noise.py:

```python
        self.src = src                                                                        
        self.dtype = self.src.dtype                                                           
        self.L = src.L                                                                        
        self.n = src.n   
```

We should double check that these *aren't* ever  different, and if so, simplify by referring to the `src` if that's where the values come from.

### PR DESCRIPTION
**Pull request by chris-langfield**
Issue #531 

As a precaution I checked through the codebase, but as far as I can tell there is no situation in which the number of images or the resolution of an Estimator (`NoiseEstimator`, `CovarianceEstimator`, `MeanEstimator`, etc.) should be different from those of the `Source` with which it was instantiated. It makes more sense to just get these from the Source to avoid the suggestion that these attributes of the Estimator are independent.

### CODE REVIEW

**Comment by garrettwrong** [comment]
I could see this potentially causing some merge conflicts (not for me, :D) , but that's just a hunch. If its not critical for another patch you might want to wait on it.

**Comment by chris-langfield** [comment]
> I could see this potentially causing some merge conflicts (not for me, :D) , but that's just a hunch. If its not critical for another patch you might want to wait on it.

Thanks for the heads up. This is sort of cosmetic / cleanup so I think it can wait

**Review by j-c-c — APPROVED** [review]
This looks good to me.

**Review by janden — APPROVED** [review]
LGTM

**Pull request merged**
