### PR TITLE
norm_assoc_legendre factorial

### PR DESCRIPTION
**Pull request by garrettwrong**
This was generating numerical warnings for relevant resolutions.

I refactored the math a little to move the square root inside the factorial product. 

I'm hoping that avoids this problem for practical 3D reconstructions.

Relates to #528 and #525 . One of several problems.

### CODE REVIEW

**Review by j-c-c — COMMENTED** [review]
Looks good. The math checks out on my end.

**Comment by garrettwrong** [comment]
@janden , I think you were right and we'll need to deal with this now even to cover 64x64x64....

**Comment by janden** [comment]
Code exists to do this in the way I suggested here: https://github.com/PrincetonUniversity/aspire/blob/master/basis/norm_assoc_legendre.m. It's not perfect, but it should work for our purposes.

**Comment by garrettwrong** [comment]
Thanks @janden . Some good news, that appears to resolve some of the issues I was seeing with FFB3D.  I am able to run a sanity check reconstruction for a resolution of 65 now.  ~Unfortunately it breaks one of our hard coded unit tests (looking next)...~

FB3D still crashes for meaningful resolutions, and we still have the (FFB3D evaluate) ill conditioning reported in the other issue... but all in all this is positive progress.

**Review by janden — APPROVED** [review]

**Pull request merged**
