### PR TITLE
Downsample bug for integer offsets

### LINKED ISSUE #926: `image.downsample` broken for source with integer `offsets
Example script for bug:
```
from aspire.source import Simulation
src = Simulation(offsets=0)
src.downsample(4)
```
Gives the following error:
```
UFuncTypeError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 src.downsample(4)

File ~/Work/ASPIRE-python.Symmetry_Groups/src/aspire/source/image.py:119, in as_copy.<locals>.wrapper(self, *args, **kwargs)
    117 obj_copy = copy.deepcopy(self)
    118 func_copy = copy.deepcopy(func)
--> 119 func_copy(obj_copy, *args, **kwargs)
    120 return obj_copy

File ~/Work/ASPIRE-python.Symmetry_Groups/src/aspire/source/image.py:699, in ImageSource.downsample(self, L)
    697 ds_factor = self.L / L
    698 self.unique_filters = [f.scale(ds_factor) for f in self.unique_filters]
--> 699 self.offsets /= ds_factor
    701 self.L = L

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

### PR DESCRIPTION
**Pull request by j-c-c**
Resolves issue #926

### CODE REVIEW

**Review by garrettwrong — CHANGES_REQUESTED** [review]
Fix should be fine. 

Please add a quick test that exercises this bug (lines from your bug report might be fine).  The current examples and tutorials work around it.

Thanks!

**Review by garrettwrong — CHANGES_REQUESTED** [review]
Did you confirm your test case exercises the bug before you sent it to me?

**Comment by j-c-c** [comment]
> Did you confirm your test case exercises the bug before you sent it to me?

Yes

**Comment by garrettwrong** [comment]
> > Did you confirm your test case exercises the bug before you sent it to me?
> 
> Yes

Whats the default simulation resolution?

**Review by garrettwrong — DISMISSED** [review]

**Review by garrettwrong — APPROVED** [review]

**Review by janden — APPROVED** [review]

**Pull request merged**
