### PR TITLE
initial programmatic import sort

### LINKED ISSUE #179: Standardize Imports
Standardizing the import ordering helps keep the code consistent and can often highlight strange dependency ordering problems (or at least make them more deterministic). Ideally those problems should not exist, but in reality it happens.  Generally good practice, and makes the code look/feel less homebrew.

Once they are in order, keeping them in order when changing is just mimicking, so shouldn't be too much of a burden. I have a PR where I've done the bulk work. I figure this quiet time is best time to bring it in.

I was planning to put some automation in to check this in the future, but I haven't made those issues yet.

You might ask why I am doing this.  Well, my first project I found a circular dependency in between block diagonal code and cell.py code, and I think this might have caught it... as an example.

### PR DESCRIPTION
**Pull request by garrettwrong**
Since this touches a lot of stuff, I figure it is good to try and do it between bigger projects.

Closes #179

### CODE REVIEW

**Comment by janden** [comment]
Is this done using isort? If so, will there be a way of automating this? Guess it's hard to do as part of a CI other than making sure that isort doesn't change anything with each PR.

**Comment by garrettwrong** [comment]
yes, isort.

Automation would be with something like `tox` for example. I didn't make that card yet :).

**Comment by janden** [comment]
Ok good. Just curious.

**Review by janden — APPROVED** [review]

**Comment by garrettwrong** [comment]
Updated this to put aspire below standard and third party libraries. That is controlled by `.isort.cfg`. Otherwise similar to before, just with aspire imports moved down.

@junchaoxia , can you let me know if this is an okay time to merge this in for you by giving it a review when you have a chance? Thanks

**Review by junchaoxia — APPROVED** [review]
Useful tool. Thanks.

**Review by janden — APPROVED** [review]

**Pull request merged**
