### PR TITLE
Test est shifts fail

### PR DESCRIPTION
**Pull request by janden**
```
$ python3 -m pytest tests -k est04EstShifts
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /shared/home/janden/projects/aspire-python, inifile: pytest.ini
plugins: cov-2.8.1
collected 184 items / 183 deselected / 1 selected                              

tests/test_orient_sync.py::OrientSyncTestCase::test04EstShifts 
-------------------------------- live log call ---------------------------------
2020/08/10 22:10:46 Trying NFFT backend finufft
2020/08/10 22:10:46 NFFT backend finufft usable
2020/08/10 22:10:46 Trying NFFT backend pynfft
2020/08/10 22:10:46 NFFT backend pynfft not usable
2020/08/10 22:10:46 Selected NFFT backend = finufft
2020/08/10 22:10:47 Applying forward transformations in pipeline
2020/08/10 22:10:47 All forward transformations applied
2020/08/10 22:10:47 Loaded 64 images
2020/08/10 22:10:47 Represent 2D image in a polar Fourier grid
2020/08/10 22:10:48 Top 10 eigenvalues from synchronization voting matrix: [-7.91710665  7.82478962  7.99980306  8.32795049  8.71195868  9.55840775
                     11.04110791 30.8483627  33.35265287 35.32929706]
FAILED                                                                   [100%]

=================================== FAILURES ===================================
______________________ OrientSyncTestCase.test04EstShifts ______________________

self = <tests.test_orient_sync.OrientSyncTestCase testMethod=test04EstShifts>

    def test04EstShifts(self):
        results = np.load(os.path.join(DATA_DIR, 'orient_est_shifts.npy'),
                          allow_pickle=True)
>       self.assertTrue(np.allclose(results, self.est_shifts))
E       AssertionError: False is not true

tests/test_orient_sync.py:72: AssertionError
----------------------------- Captured stdout call -----------------------------
2020/08/10 22:10:46 Trying NFFT backend finufft
2020/08/10 22:10:46 NFFT backend finufft usable
2020/08/10 22:10:46 Trying NFFT backend pynfft
2020/08/10 22:10:46 NFFT backend pynfft not usable
2020/08/10 22:10:46 Selected NFFT backend = finufft
2020/08/10 22:10:47 Applying forward transformations in pipeline
2020/08/10 22:10:47 All forward transformations applied
2020/08/10 22:10:47 Loaded 64 images
2020/08/10 22:10:47 Represent 2D image in a polar Fourier grid
2020/08/10 22:10:48 Top 10 eigenvalues from synchronization voting matrix: [-7.91710665  7.82478962  7.99980306  8.32795049  8.71195868  9.55840775
 11.04110791 30.8483627  33.35265287 35.32929706]
------------------------------ Captured log call -------------------------------
2020/08/10 22:10:46 Trying NFFT backend finufft
2020/08/10 22:10:46 NFFT backend finufft usable
2020/08/10 22:10:46 Trying NFFT backend pynfft
2020/08/10 22:10:46 NFFT backend pynfft not usable
2020/08/10 22:10:46 Selected NFFT backend = finufft
2020/08/10 22:10:47 Applying forward transformations in pipeline
2020/08/10 22:10:47 All forward transformations applied
2020/08/10 22:10:47 Loaded 64 images
2020/08/10 22:10:47 Represent 2D image in a polar Fourier grid
2020/08/10 22:10:48 Top 10 eigenvalues from synchronization voting matrix: [-7.91710665  7.82478962  7.99980306  8.32795049  8.71195868  9.55840775
                     11.04110791 30.8483627  33.35265287 35.32929706]
=================== 1 failed, 183 deselected in 3.72 seconds ===================

```

### CODE REVIEW

**Comment by garrettwrong** [comment]
@janden @junchaoxia , I took this branch and reverted the package stuff that happened end of june all the way back to `master` by:

```
 git checkout origin/master setup.py
 git checkout origin/master environment.yml
 git checkout origin/master requirements.txt
```

I still get the unit test failure.  There is a problem. Its not CI or the other branches.  I think you have a bad merge/rebase situation.

Diff from the `test_est_shifts_fail` branch compare with `origin/test_shifts` returns more than I expected if the `test_shifts` was really up to date. (It looks like it was only half kept up to date, taking some but not all changes from `develop` as it moved, fun). I was expecting to _only_ see the packaging changes.  Perhaps instead of the merge, you might try to rebase this code and manually resolve the conflicts in a separate area.  This might force you to work through the actual conflicts. I think because the conflicts were already introduced, partially fixed but marked resolved git isn't quite getting this right. Regardless, the diff is pretty much a list of files I would be concerned about and need to be handled manually. Good luck.

```
(aspire_foo_master) ➜  ASPIRE-Python.foo git:(test_est_shifts_fail) git diff origin/test_shifts --stat
 .travis.yml                                        |   2 +-
 README.md                                          |  42 +++++++++++++++++----------
 azure-pipelines.yml                                |  12 ++++----
 environment.yml                                    |   2 +-
 requirements.txt                                   |  23 ---------------
 setup.py                                           |  35 +++++++++++++++-------
 src/aspire/aspire/class_averaging.py               |  37 +++++------------------
 src/aspire/aspire/em_classavg/em.py                |   5 ++--
 src/aspire/aspire/em_classavg/test_progressbar2.py |  13 ---------
 src/aspire/aspire/preprocessor.py                  |   1 -
 src/aspire/aspire/utils/array_utils.py             |   1 -
 src/aspire/aspire/utils/compare_stacks.py          |  14 ++-------
 src/aspire/basis/polar_2d.py                       |  51 +++++++++++++++++++-------------
 src/aspire/orientation/__init__.py                 |   7 +----
 src/aspire/utils/misc.py                           |  40 ++++++++++++++++++++++++-
 tests/test_PolarBasis2D.py                         | 116 ++++++++++++++++++++++++++++++++-----------------------------------------
 16 files changed, 192 insertions(+), 209 deletions(-)
```

**Comment by junchaoxia** [comment]
@Janden @garrettwrong Before I go ahead to do something, I want to confirm that  `test_est_shifts_fail` is a clone branch of `orientation` . My `test_shifts`  also is a branch of `orientation` but with a few new commits for printing out information related the shift equations. The diff result between `test_est_shifts_fail` and `test_shifts` should be the changes added for  printing out information related the shift equations and shoud be identical to the diff result  between `orientation` and `test_shifts`   as shown below: 

 [junchaox@tigercpu ASPIRE-Python_git]$   git diff test_shifts --stat
 .travis.yml                            |  2 +-
 azure-pipelines.yml                    | 12 ++++++------
 src/aspire/orientation/__init__.py     |  7 +------

**Comment by garrettwrong** [comment]
In our meeting we discussed that this branch `test_est_shifts_fail` is `test_shifts` (which you've provided) merged with `develop`, or at least what `develop` was yesterday afternoon. This is the case that the CI system was failing on.

I don't really know what you are asking.  I just checked diffs (you can do this) and I see similar problems between `orientation` (or `test_shifts`) and `develop` as it was. There are actually less diffs between `test_est_shifts` and `develop` because some merging was done bringing it more up to date.

I've provided a pretty detailed diagnosis at this point. Merging this branch with develop is yielding a regression.  My intuition is that it is from a problematic integration(s) you've done along the way.  One way to try and fix this is to attempt a very careful rebase to the head of develop, which hopefully forces you to work through the regression(s) and gets the code up to date.

**Comment by junchaoxia** [comment]
@janden @garrettwrong  The latest two merges of `orientation` with `develop`  are June 25 and Jun 23. The updates on `develop` branch after June 25 are not included in `develop`. So are you guessing those updates on `develop` after June 25 generate the problem?  I rerun the PR 214 based on `develop` this morning. Now all tests on different platforms are passed. If there is a code rebase/merging problem, why the test results are different at different time? This is the biggest confusing to me.

**Comment by garrettwrong** [comment]
I believe it to be fact we have reproduced this issue locally, outside of CI. I could do it again from scratch, but...? I went out of my way to confirm that the single small set changes (to a few package versions) after June 25 were not related. I did this by taking specific files from `master` and repeating the test.  I have provided some of the commands to do the same.  That and the remaining diagnosis was more time than I had hoped to spend on this. The deal was if it was not related to those changes, I would be handing it back to you....

Regarding 214, you originally pushed that as a merge into your own branch (not `develop`). We discussed that this would have been where the integration tests were based against, and I see no evidence they have been rerun with other targets. We discussed this together yesterday, but there was a lot going on, because we were chasing red herrings at the time.

Maybe you can go through the process we did yesterday again to reproduce the issue independently to start. I hope that would clear up some confusion.

**Comment by junchaoxia** [comment]
@janden @garrettwrong  I created a local branch `orient_rebase` by rebasing to `develop` branch on Aug 11 and manually solved several conflicts.  Now the `test04EstShifts` of rebased branch fails when I run it locally on the head node of Tiger cluster. Since the `orientation` branch is based on `develop` of June 25 and running without problem locally, I think we can say that the problem was introduced between June 25 and Aug 11?

**Comment by garrettwrong** [comment]
wow, can i just pay someone on fiver to do this? This is really not effective.

**Comment by janden** [comment]
> I created a local branch orient_rebase by rebasing to develop branch on Aug 11 and manually solved several conflicts.

Ok good. So this should contain all of the new commits in `orientation` added on top of the current `develop`, correct?

> Now the test04EstShifts of rebased branch fails when I run it locally on the head node of Tiger cluster.

Good, so we're reproducing the test failure. We now have a linear history, which should make it easier to spot where that failure is introduced.

> Since the orientation branch is based on develop of June 25 and running without problem locally, I think we can say that the problem was introduced between June 25 and Aug 11?

Here I don't follow. If you run the tests on the most recent `devel` (the one from Aug 11), the tests pass, correct? When you run the tests on this `orient_rebase` branch, the test fails, so it stands to reason that the test failure is introduced on some commit between those two (you could find it using `git bisect`). I'm not saying there's not some interaction between the recent changes to `develop` and those in `orientation` that's causing the failure, but it should be possible to narrow down the problematic commit by looking through the history of this `orient_rebase` branch. Does this make sense?

**Comment by junchaoxia** [comment]
> Ok good. So this should contain all of the new commits in orientation added on top of the current develop, correct?

Yes. That is what I did. 

> Good, so we're reproducing the test failure. We now have a linear history, which should make it easier to spot where that failure is introduced.

Yes. I can reproduce the error locally. It is easier to trace the results from the changes of different branches.  


> Here I don't follow. If you run the tests on the most recent devel (the one from Aug 11), the tests pass, correct? When you run the tests on this orient_rebase branch, the test fails, so it stands to reason that the test failure is introduced on some commit between those two (you could find it using git bisect). I'm not saying there's not some interaction between the recent changes to develop and those in orientation that's causing the failure, but it should be possible to narrow down the problematic commit by looking through the history of this orient_rebase branch. Does this make sense?

Thanks. I am trying to narrow down the problem before June 25 or after June 25. The test using `orientation` branch that only includes the merges from `develop` till June 25 can be passed locally. But the test using the rebased branch, `orient_rebase`, based on `develop` of August 11 can not.  All the code for the orientation estimation is the same, the difference is including code from `develop` at different time.  This leads my consideration of something between  June 25 and August 11. Anyway, it is good to know it can be reproduced locally.

**Comment by janden** [comment]
> All the code for the orientation estimation is the same, the difference is including code from develop at different time.

Well not quite, because now the changes are being applied to the more recent `develop`, so the combined code is different. It's this that's causing the test failures.

>  This leads my consideration of something between June 25 and August 11.

Are you talking about in the `develop` branch or in the `orientation` branch? At this point, I don't think it makes sense to talk about different dates. You have a linear commit history in the `orient_rebase` branch, so you can try successive commits and see where the failure is introduced (again, you can simplify this using `git bisect`). We know that `develop` passes but `orient_rebase` fails, so the commit that introduces the failure must be somewhere in between.

**Comment by junchaoxia** [comment]
> Well not quite, because now the changes are being applied to the more recent develop, so the combined code is different. It's this that's causing the test failures.

Yes. The combinations are different. What I try to say is the code on orientation estimation its self is the same, not including the updates on develop branch different time. 

> Are you talking about in the develop branch or in the orientation branch? At this point, I don't think it makes sense to talk about different dates. You have a linear commit history in the orient_rebase branch, so you can try successive commits and see where the failure is introduced (again, you can simplify this using git bisect). We know that develop passes but orient_rebase fails, so the commit that introduces the failure must be somewhere in between.

My consideration in the previous comment is about the develop branch. Now all the orientation estimation code was moved after the develop branch of  Aug. 11.  I have checked out some of my commits yesterday, but the test on estimating shifts still failed even when I checked out my commit on May 29 when the unit tests were built initially. So I probably have to revert some commits from the develop branch. I probably will come back after updating PR 190.

**Comment by junchaoxia** [comment]
@janden @garrettwrong  OK I think I found the reason.  The original `evaluate_t` in the Polar2DBasis class was based on the original Python code which uses `finufftpy.nufft2d2many` directly and is based on `+i` definition, such as `finufftpy.nufft2d2many(self.freqs[0, :half_size], self.freqs[1, :half_size], pf, 1, 1e-15, x)` The unit test of estimated shifts was built based on this definition. However, on June 30 we downgraded the many framework to `nufft3` in the `FINufftPlan` class which uses `-i` definition such as `result_code = self.transform_function( *self.fourier_pts, result, -1, epsilon, signal)`. This will not have effect on rotational estimation but will generate shift values in the opsite direction. I will merge all updates from the `develop` into the `orientation` branch and rebuild the unit test of shifts based on the `-i` definition.

**Comment by garrettwrong** [comment]
so https://github.com/ComputationalCryoEM/ASPIRE-Python/pull/167 ?

**Comment by junchaoxia** [comment]
@janden @garrettwrong  I will push the updates back to PR #163 so that we can continue and merge.

**Comment by janden** [comment]
> This will not have effect on rotational estimation but will generate shift values in the opsite direction.

Really? The direction of the shifts shouldn't change depending on what type of polar Fourier transform we're using. Is there some other part of the code that relies on –i being +i? That should probably be changed in that case.

**Comment by junchaoxia** [comment]
@janden My observation is that the right side shift_b is opposite if I change from +i to -i but left side is the same. The related code in the following lines: 
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/orientation/src/aspire/orientation/__init__.py#L355
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/orientation/src/aspire/orientation/__init__.py#L342
https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/orientation/src/aspire/orientation/__init__.py#L341

Probably this part needs to be changed too.

**Comment by janden** [comment]
> Probably this part needs to be changed too.

By “this part” you mean the left-hand side (the operator)? Then yes. That way the shifts should stay the same (and the tests should pass).

**Comment by junchaoxia** [comment]
@janden @garrettwrong The sign to the shift functions was changed and the original unit test of estimated shifted was recovered. All tests can pass now for PR 163.

**Pull request closed without merging**
