### PR TITLE
Common Lines: `n_theta` even check

### LINKED ISSUE #792: Common-lines: `n_theta` must be even.
When using a common lines method `n_theta` must be even. There is a check here: https://github.com/ComputationalCryoEM/ASPIRE-Python/blob/fad4dfd6ebf66d4983688c5ec01d99fae7167130/src/aspire/abinitio/commonline_base.py#L72-L75

But this check needs to be moved up a few line above `evaluate_t` since `n_theta // 2` is used there.

Additionally, a note should be added to the relevant docstrings.

### PR DESCRIPTION
**Pull request by j-c-c**
This PR closes #792

Moves the check for `n_theta` even above polar fft step which requires `n_theta` to be even. Note added to docstring param.

`NotImplementedError` now raised with message "n_theta must be even".

### CODE REVIEW

**Comment by garrettwrong** [comment]
Okay cool this fixes the check. 

If we fix Polar2D will we still need this check for CL code?  Can you make an issue about fixing Polar2D and if relevant,  removing this check after. I suspect it might not be too bad to fix Polar2D, but I understand the purpose of this PR is just to not crash.

**Review by garrettwrong — CHANGES_REQUESTED** [review]
If fixing polar2D is not the only reason this needs to be even, please add a unit test covering this branch.  Otherwise, don't worry about the extra work for the ut now.

**Comment by j-c-c** [comment]
> Okay cool this fixes the check.
> 
> If we fix Polar2D will we still need this check for CL code? Can you make an issue about fixing Polar2D and if relevant, removing this check after. I suspect it might not be too bad to fix Polar2D, but I understand the purpose of this PR is just to not crash.

Both the CL code and the Polar2D code take advantage of only needing half of the polar Fourier rays (due to the conjugate symmetry) for computations. Maybe this PR should just be fixing the Polar2D code, ie. adding a check for `n_theta` even there.

**Comment by garrettwrong** [comment]
Adding a check is not fixing it :).  Adding an additional check is a good idea. Let's add the check in both places (since you say they both depend on being even) and unit test that both those checks work to close this.

We can address fixing (or not fixing) the code handling evens as a separate issue.

**Review by garrettwrong — APPROVED** [review]
lgtm. Please make that issue about improving Polar2d. Thanks

**Comment by j-c-c** [comment]
> lgtm. Please make that issue about improving Polar2d. Thanks



> lgtm. Please make that issue about improving Polar2d. Thanks

Created issue #844.

**Pull request merged**
