### PR TITLE
test stability of shift equations 

### PR DESCRIPTION
**Pull request by junchaoxia**

### CODE REVIEW

**Comment by janden** [comment]
Is this ready for review? Says it's a draft right now. Can you provide a description of what the PR is supposed to do?

**Comment by junchaoxia** [comment]
@janden This PR is only used to test stability of shift equations which might be a reason why the test of estimated shifts failed in the PR #163 from including the orientation estimation method. More information was printed out  but the test did not fail at different time and commits. So probably it is not related to the code.

**Comment by janden** [comment]
So I should not review it, is that correct? It says a review was requested, but maybe this happens automatically since I'm the code owner?

**Comment by junchaoxia** [comment]
Thanks. Not need to review it not.  I will request it again if I have some changes to merge into develop.

**Pull request closed without merging**
