### PR TITLE
Deprecate Python 3.6

### LINKED ISSUE #320: Python 3.9
Following #313 we will have the product of python 3.6 3.7 3.8 x stable,dev environments under test with travis ci.  Currently some packages are not available for python 3.9 which was just released.  Instead of working around that temporarily, I think we can just wait to re-evaluate and add these lines at a later date.

```
    # Some 3.9 depends are not yet avail, 11/06/2020.
    # - python: 3.9
    #   env:
    #     - TOXENV=py39-stable
    #     - TOXENV=py39-dev
```

### PR DESCRIPTION
**Pull request by garrettwrong**
* Drop 3.6 in favor of 3.7 (new stable default)
* Add 3.10

Closes #320

### CODE REVIEW

**Comment by garrettwrong** [comment]
Reminder, changes like this will require adjusting the expected status checks on Github. In this case that means adding those named Python37 and removing Python36.  I will do this once the changes are otherwise settled since it will conflict with other PRs....

Also, it looks like MS Azure is deprecating one of the windows images we use this month, so I'll make an issue about that. Might update it in this PR as well.

**Comment by garrettwrong** [comment]
Removed Windows 2016 following the recommendation for GH Actions below.  We already have `windows-latest` implemented and that should be adequate.

https://github.com/actions/virtual-environments/issues/4312

**Review by chris-langfield — APPROVED** [review]
Cloned repository and did my own `git grep`s to check for stray Python 3.6 mentions.

Confirmed that new pandas and numpy versions are the most recent supporting Python 3.7, and scipy is latest version overall.

There is still a comment in `src/aspire/utils/importlib_legacy.py` referring to dropping Python 3.6 in the future, but this file will be removed anyway once this PR is merged so I think it's okay to leave them. I will note this on #503 

Thanks!

**Comment by garrettwrong** [comment]
@j-c-c @chris-langfield . I just updated status checks for `develop`. Going to merge this in. Will touch base on updating your branches and I will show you both how to update the status checks for `master` during our standup.

**Pull request merged**
