### PR TITLE
Deprecate ensure

### LINKED ISSUE #578: Replace `ensure` with `assert`
See discussion on #522 

`ensure` is just a wrapper for `assert` statements. We should move towards removing this and aim to use the standard library tool. Whether as we encounter it, or as one wholesale replacement in a PR.

### PR DESCRIPTION
**Pull request by garrettwrong**
Closes #578

### CODE REVIEW

**Review by chris-langfield — APPROVED** [review]
Looked through for any mishaps your script might have made but found none. Also did an extra git grep to make sure we got all of them. Thanks!

**Review by janden — APPROVED** [review]
Thanks.

Just out of curiosity, I suppose this
```
    assert statements in Python are sometimes optimized away by the compiler, and are for internal testing purposes.
    For user-facing assertions, we use this simple wrapper to ensure conditions are met at relevant parts of the code.
```
is in fact not the case?

**Comment by garrettwrong** [comment]
> Thanks.
> 
> Just out of curiosity, I suppose this
> 
> ```
>     assert statements in Python are sometimes optimized away by the compiler, and are for internal testing purposes.
>     For user-facing assertions, we use this simple wrapper to ensure conditions are met at relevant parts of the code.
> ```
> 
> is in fact not the case?

Well it is half true, so that is a fair question. Not true for this project.  Technically asserts can be optimized away, but only if we optimize or a user intentionally optimizes our code with special flags before attempting to use it.  This isn't something we do. It is akin to disabling logging/warnings via command line flags.

Another, seperate discussion... If there is an assert that is not for sanity check purposes, testing, or debugging, it should be converted to raise an exception.

**Comment by janden** [comment]
Ok thanks!

**Pull request merged**
