### PR TITLE
Develop ~> Main v0.12.0

### PR DESCRIPTION
**Pull request by garrettwrong**
Draft of release notes below. Please let me know if you see anything I've missed. Thanks

~I'll synch the branches and undraft once the last outstanding v0.12.0 PR is merged.~

----------

ASPIRE v0.12.0 is minor release, adding new scientific features, components, and several improvements.

This release provides the following features:

* `MicrographSimulation` component
* `MicrographSource`s with `CoordinateSource` integration
* Data Downloader utility (via `pooch`)
* `WeightedVolumesEstimator` for heterogeneous 3D reconstruction
* TIFF `Image` loading support
* Common Lines method for C2 symmetry
* `DiagMatrix` operator

Bug fixes:

* `clean_image` caching
* Apple unit test patch (following `numpy` updates)
* Rename `PolarBasis2D` to `PolarFT` and consistently use compact (real symmetric) representation

Systems/CI Updates:

* Add Python 3.11, drop Python 3.7
* Modernize Python packaging via `pyproject.toml`
* Warnings cleanup
* Migrate several tests towards `pytest.fixture`
* Modular and `pytest.fixture` based tests for Common Lines methods
* Reduce APPLE unit test time
* Apple M1/M2 arm-64 install documentation
* `cufinufft` v1.3 final adoption
* GRPC dependency updates

### CODE REVIEW

**Review by j-c-c — DISMISSED** [review]
Looks good. I don't see anything missing.

**Review by janden — APPROVED** [review]
Not sure where we would mention diag matrix and polar ft. I guess they're internal/refactoring and so are not accounted for in release notes?

**Comment by garrettwrong** [comment]
Oh, yeah, I forgot about DiagMatrix.  Can add PolarFT cleanup.

**Comment by garrettwrong** [comment]
Updated, just waiting for CI to settle ✅ .

**Review by amitsinger — APPROVED** [review]

**Pull request merged**
