### PR TITLE
Remove legacy aspire/aspire code

### PR DESCRIPTION
**Pull request by garrettwrong**
Created tag [legacy_aspire](https://github.com/ComputationalCryoEM/ASPIRE-Python/tags) to mark a commit before removal.  Using that commit it should be possible to create a branch later, or otherwise recover the code in the state it was in today.

Removes the `src/aspire/aspire` directory, and related doc page.

Also includes a minor typo fix in `conf.py` I found when manually rebuilding the docs.

### CODE REVIEW

**Review by janden — CHANGES_REQUESTED** [review]
We should also remove code that depends on `aspire.aspire`. From what I understand, this should be restricted to `aspire.commands.aspire`, but there may be others.

**Comment by garrettwrong** [comment]
Gotcha, yeah, I must have missed it because there were no tests... Will do.

**Comment by garrettwrong** [comment]
Updated. Besides a historical comment (im_translate2) grep for `aspire.aspire` is clean now. I should have checked the first time.

We will be able to bring back something similar or refresh this code, but I'm hoping we can keep it more consistent and constantly/automatically tested this time its integrated so it doesn't diverge as much...

**Comment by janden** [comment]
Sorry I was unclear. It's only the `aspire.py` file that needs to be removed. From what I understand, the others (`apple.py`, `denoise.py`, etc.) still work. We will probably want to rework the interface at some point, but they're not broken, so let's keep them.

**Comment by garrettwrong** [comment]
Okay, sure, I'll need to put the quickstart back then. I should have it ready in a few. Thanks

**Comment by garrettwrong** [comment]
Restored the quickstart docs, rebased. Sorry for the noise.

**Review by janden — APPROVED** [review]

**Pull request merged**
