### PR TITLE
Force finufft signals to be complex

### PR DESCRIPTION
**Pull request by garrettwrong**
This should work around the changes put in FINUFFT v2.0.4. Also it seems like their project lead might prefer to enforce this instead of casting in the future.

### CODE REVIEW

**Comment by garrettwrong** [comment]
Closes #572 

Deprecates #573

**Comment by garrettwrong** [comment]
See https://github.com/flatironinstitute/finufft/pull/203

**Review by janden — APPROVED** [review]
So do I understand correctly in that 2.0.3 allowed real dtypes and did the cast to complex, but that 2.0.4 did not cast (but allowed real dtypes, hence the bug)?

**Comment by garrettwrong** [comment]
Yes, that is correct. Prior versions of FINUFFT cast real signals to complex for the user.

**Pull request merged**
