### PR TITLE
Seg Fault Issue 150

### LINKED ISSUE #150: Intermittent Seg Faults (OSX, Linux)
Since I have started working with the code it has randomly encountered a seg fault in the unit tests (python setup.py test).  I have also occasionally seen the same in the CI pipeline logs.

Initially, I thought maybe it was just me, then OSX, then just OSX and my Fedora desktop.  However, it continued to happen from time to time even when I exclusively run on the Princeton cluster.  I wrote a script to loop over the test suite and found that the develop branch segfaults about 4% of time at Princeton. (Two test batches 7/100, then 2/100 attempts seg faulted on a dedicated node).  This is somewhat unusual and concerning for python code.

I have a few hunches, and also Vineet suggested a few places I might consider.  I am looking into it (running a loop in bg trying to catch one in gdb to get a trace). My suspicion is that it occurs during some multi-threading in test_apple. 

Don't worry, it might be benign (sometimes thread exits are dirty and just need to be handled).  Hope to know more soon.

### PR DESCRIPTION
**Pull request by garrettwrong**
This appears to be one of the issues that caused spurious seg fault crashes in the ApplePicker unit test. I have run the test suite with this change a few hundred times now, and have not been able to provoke a seg fault.

I will be curious if this also improves the OSX stability.

The issue appears to be that pyfftw is not totally thread safe, and we call it in a threadpool.  Since the threadpool may help with IO ops in the grander scheme of things, I left it in, but lock around the problem area with a mutex.  When ApplePicker is reviewed, we may consider dropping threading in favor of something more pythonic (process/async).

Closes #150

### CODE REVIEW

**Review by junchaoxia — COMMENTED** [review]
Thanks. I have not encountered test failures due to this issue for a long time. Vineet tried to fix this issue last year probably by moving around the initialization but I forgot whether he included the updates or not.

**Comment by garrettwrong** [comment]
Interesting. It was failing a non trivial percentage of the time in our CI, but our CI was generally broken/ignored for many months when I came on board, so I am not surprised it went unnoticed.  It has happened a few times since in our CI. Its not just my machines, though it has happened on both my mac and multiple linux machines.  This particular issue always has a similar traceback, so we can tell it apart...  If I can get my desktop back online (ugh) I'll add a traceback. The old CI logs have been cleaned up.  It is admittedly just a few percent of the time, so the expectation with which you would see it depends on the frequency of running the applepicker test (I tend to be running whole collection often often since I am twiddling structures).

I think Vineet fixed a separate issue that manifested similarly. That we've had multiple issues in this threading area affirms my stance on the topic :).

I have not been able to tickle the condition after this patch, but I am also not 100% sure this will get rid of all threading based problems in that neighborhood. Frankly, if this section gives us any more trouble I am going to strongly recommend gutting any threading in ASPIRE python code. It is an advanced technique we may not have the resources to fully appreciate... but for today we can try to work with what we've got and the original intentions there.

**Comment by garrettwrong** [comment]
@junchaoxia , it seems like you took a look, but I don't see a review.   If you don't see any issues with the code, can you provide a review so that it is ready for Joakim when he returns? Thanks!

**Comment by garrettwrong** [comment]
I just wanted to point out the thing which was never noticed happening has already happened once in CI just today ;)... On a change set that involved editing a README file.  FWIW.  I attached the build log because they tend to get cleaned up quickly.

[build_log.txt](https://github.com/ComputationalCryoEM/ASPIRE-Python/files/5043010/build_log.txt)

**Comment by junchaoxia** [comment]
@garrettwrong So the problem of threading is still existing? My previous notices to the failures of CIs were mostly from the test Cov3D which was solved temporarily by increasing the atol values, and also many due to the internal reasons from building machines.

**Review by janden — APPROVED** [review]
LGTM.

For what it's worth, my understanding is that FFTW (and hence pyfftw) is not thread-safe during the planning stage. Execution, however, is. So if performance is an issue, you could move the `cls(a, b)` calls outside of the mutex. On the other hand, this works, so we should just leave it.

**Comment by garrettwrong** [comment]
I don't know that either of those two things have anything to do with threading.  At some point Vineet may have worked on at least one threading bug, but it was neither of the things you are suggesting.

I don't know what you are asking exactly. I have not seen the problem with this patch, but that is not the same as saying I have fixed every single threading bug introduced by bringing threading into Python.  If you are asking whether in `develop` this problem exists, yes, absolutely, it happens like 5% of the time since the threading code was introduced.

**Comment by garrettwrong** [comment]
I tried that first, based on what I assume were the same posts you've read :), and it was not the case for us in practice.  That could have been because I was initially hitting the other transform, but regardless.  I wasn't totally confident the remarks are read were about the python side or the FFTW side. I'd bet they just shook a stick at what worked :).

TBH, threading in Python should probably be avoided.  It was naively done at way too high a level here and caused the typical problems. This would be the last issue I would devote any time to fixing it. Next time it should get ripped out mercilessly.

**Comment by janden** [comment]
> I tried that first, based on what I assume were the same posts you've read :), and it was not the case for us in practice.

Ah. That's interesting. Could by the PyFFTW part then. I've seen this done with FFTW (not pyfftw) where you end up having to create one plan per thread and then things (seem to) work out.

> TBH, threading in Python should probably be avoided.

Agreed. If things are stable now, though, it can wait.

**Comment by junchaoxia** [comment]
I agree to merge it first if it is stable.

**Review by junchaoxia — APPROVED** [review]

**Pull request merged**
