### PR TITLE
Distinguish between pairs and loops in a STAR file

### LINKED ISSUE #463: Distinguish between key value pairs and loops in STAR files
Currently we represent STAR files as `OrderedDict`s of pandas `DataFrame` objects. The implementation, when reading a STAR file, treats a regular set of key-value pairs, and a single-line loop the same way, mapping to a single-row `DataFrame`. Ideally we should be able to distinguish between these in our representation.

The key-value form in a STAR file looks like:
```
data_
_field1    val2 
_field2    val2
...
```

While a single row loop looks like:
```
data_
loop_
_field1 
_field2
_field3
val1     val2     val3
```

The code handling the reading and writing of files is in `aspire.storage.starfile` and uses the external `gemmi` library.

The goal would be to alter how the `gemmi.Document` representation of the StarFile is converted in our code. `gemmi` itself does make this distinction with `Loop` and `Pair` objects.

https://gemmi.readthedocs.io/en/latest/cif.html
https://project-gemmi.github.io/python-api/gemmi.cif.html

### PR DESCRIPTION
**Pull request by chris-langfield**
Addresses #463 by changing the `OrderedDict` of `DataFrames` to an `OrderedDict` of `DataFrame` or `dict`, for loops and pairs respectively. Type checking is added to `starfile.py`. Tests adjusted accordingly, with one redundant test removed.

### CODE REVIEW

**Comment by chris-langfield** [comment]
Note in particular that means the STAR file created by `estimate_ctf` will always be a loop #469, recreating the previous behavior of the code, and ensuring exact compatibility with Relion

**Review by garrettwrong — DISMISSED** [review]
Neat, seems like it worked out okay.  Thank you.

**Comment by garrettwrong** [comment]
Looks like you might want to try rebasing or merging latest develop for ubuntu 16 to go away.

**Comment by chris-langfield** [comment]
Hm, I tried fetching and merging latest from develop right before pushing. Will try again. Thanks

**Comment by garrettwrong** [comment]
The logs look like your used master instead... Try this

git fetch
git rebase origin/develop

**Review by janden — APPROVED** [review]
Cool! So if I understand correctly, `testData` makes sure that the dicts are written out as pairs, not loops of length one?

**Comment by chris-langfield** [comment]
> Cool! So if I understand correctly, `testData` makes sure that the dicts are written out as pairs, not loops of length one?

You're referring to `testWriteReadWriteBack` (the way the deltas were displayed was confusing). And yes that's the intent! Thanks

**Pull request merged**
