### PR TITLE
Missed img vol return tutorial updates

### PR DESCRIPTION
**Pull request by garrettwrong**
Somehow these were missed.

We will be adding doc building to the CI jobs that run on "Review" readiness, since I forgot these (my bad).

### CODE REVIEW

**Comment by garrettwrong** [comment]
Moving to merge this so `develop` docs will build.

Discussed converting the older scripts towards using the gallery formatting so we can just avoid the ugly subplot usage. (Will make an issue).

**Review by j-c-c — APPROVED** [review]
This looks good. Aside from the one `vol` plot in experimental I couldn't find any other instances.

**Review by janden — APPROVED** [review]
Looks good.

There's an interesting point here, though: we have to call `copy` on the `ndarrays` returned by `asnumpy` to avoid modifying the original `Image`? We may want to consider forcing `asnumpy` to make a copy (or to mark it read-only) to avoid this issue. This may be less important to `Image`s, but when they're part of a source, we certainly don't want people to go around modifying them by accident (especially if the sources are to be seen as immutable).

**Comment by garrettwrong** [comment]
I agree that is a concern.  Disabling writable is probably the best compromise to avoid unneeded deep copies.  I'll put that together. Thanks!

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html

**Pull request merged**
