### PR TITLE
Fix sign arg that was forcing a unit test reference change

### LINKED ISSUE #170: nufft isign
There is apparently some algorithm code that overrides the default isign convention setting used in the various nufft packages.

To support that override (and any others I am not aware of yet) using our classes requires adding isign to the nufft Plan class.  This should be expected to work for the same for any backend that has an isigin setting available or raise useful message if a user attempts something that is not supported.

### PR DESCRIPTION
**Pull request by garrettwrong**
@junchaoxia , if you would like to keep the unit test data the same, I plumbed the isign argument through so you can use it from the nufft class to reproduce the original results.

If you decide to keep I would recommend squash these commits together.  This would fixup swapping the unit test data.

I don't know whether this isign override or the default is more appropriate for this polar basis class usage in the future... but this is how you can over ride it if you need. It will work the same for the other cufinufft backend, and have the same defaults when that code is ready for merging.

Closes #170 .

### CODE REVIEW

**Comment by garrettwrong** [comment]
Maybe @janden knows which isign value we'd want? (I think we want the plumbing either way)

**Review by junchaoxia — COMMENTED** [review]
It is great to have this option to change the sign for the purpose of reproducing the previous result. For the final product I would like to change the code of orientation estimation to make the consistent representation for different submodules. I took some quick tests, the estimated orientation angles are the same since in common line equation the sign effects get cancelled out but there are some differences in estimated shifts which directly use the evaluate_t result. So I prefer to including your updates to the Finufft class but changing the unit tests for Polar2Dbasis to use the same sign.

**Comment by garrettwrong** [comment]
Okay, great. I'd like to wait for Joakim to confirm the same (mainly bc I think that is suggesting test results changing).  I can make the change and push it here in the mean time.

Generally in the future, it will be easier for me to keep track of things if we don't mix something "sciency" that might change unit tests, with a different code change that should not change any results in the same PR for a patch sized feature. At the very least maybe not same commit.  It is easy to confuse things.

**Comment by janden** [comment]
The `isign` argument, as far as I can tell, is a quirk of the Finufft interface (and its predecessor the CMCL Nufft library). As you point out, the Chemnitz Nfft code does not support this. It's not needed since you can achieve the same result by flipping the sign of the frequencies. I suggest we keep the interface simple and leave the `isign` out.

**Comment by junchaoxia** [comment]
OK. So this PR is not necessary. I will make the updates to my PR.

**Comment by janden** [comment]
Ok. Closing.

**Pull request closed without merging**
