### PR TITLE
Dtype of `Simulation.filter_indices`

### PR DESCRIPTION
**Pull request by chris-langfield**
Quick fix, filter indices should not be floats.

### CODE REVIEW

**Comment by garrettwrong** [comment]
Thanks Chris. This looks like a legit bug.  I'm sorry I did not catch this during code reviews. Dtypes are dangerous... This would be a good time to fix it across all `Sources`.

Joakim found it, I think we just didn't check it was fixed wholesale.

https://github.com/ComputationalCryoEM/ASPIRE-Python/issues/604

**Comment by chris-langfield** [comment]
Double checked the other sources as well, they look good

**Review by garrettwrong — APPROVED** [review]
Looks good, thanks.

**Review by j-c-c — APPROVED** [review]
Looks good!

**Comment by garrettwrong** [comment]
Merging.

**Pull request merged**
