### PR TITLE
3D Downsampling

### LINKED ISSUE #617: 3D Downsampling
#606 will close #140 by making our 2D downsampling method identical to the MATLAB code.

3D downsampling, (i.e. `Volume.downsample()`) currently uses the ported `downsample` method sitting in `aspire.image.preprocess`. This relies on the same principle as the new 2D method but is not identical. 

This `downsample` method takes 1,2, or 3 dimensional inputs, and can downsample to custom sizes. It is much more general than the `Image.downsample()` method we just replaced. We'll want to clean up this 3D downsampling method and see if we can break off a `crop_pad_3d` method for Volumes specifically.

### PR DESCRIPTION
**Pull request by chris-langfield**
Closes #617

### CODE REVIEW

**Comment by chris-langfield** [comment]
This breaks hardcoded tests in `test_orient_sync` and `test_covar2d`. Perhaps we should implement a `legacy_downsample` or something like that. Or we could regenerate those hardcoded tests?

**Comment by chris-langfield** [comment]
This method is exactly the same as the previous method, but spelled out more explicitly and with the same checks and rigor applied to the 2D case.

The center-points logical check is only precise up to `5e-2` for 3D, whereas it is perfect for 2D. Even when I tried implementing this 3D algorithm slightly differently using `centered_fftn`s, the `5e-2` was still as good as it could get.

**Comment by chris-langfield** [comment]
Removed tuple argument for downsample size as I don't expect that we will support downsampling to a non-cubic volume anytime soon, but can discuss

**Comment by chris-langfield** [comment]
Update on tolerance level for each 3D downsample case:

Changing the anisotropy or the max/min sigmas shuffles things a bit but in general we're seeing that even to even is by far more accurate than the other 3 cases. 

@janden I might need a nudge in the right direction of how to go about investigating further. Thanks!

With current sigmas

```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 1e-2
Odd to Even (65,32): 5e-2
Odd to Odd (65,33): 5e-2

```
Anisotropy Removed:
```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 5e-2
Odd to Even (65,32): 1e-2
Odd to Odd (65,33): 1e-2

```

Large sigmas removed (0.3)
```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 5e-2
Odd to Even (65,32): 1e-2
Odd to Odd (65,33): 1e-2

```
Small sigmas removed (0.1)
```
Even to Even (64,32): 5e-5
Even to Odd (64,33): 1e-2
Odd to Even (65,32): 1e-2
Odd to Odd (65,33): 1e-2

```

**Review by j-c-c — APPROVED** [review]
This looks good to me. The parameterized tests are really clean. It would be nice to figure out what's happening with the CenterPoint test. I would be interested to see the even-to-even accuracy with a different pairing, ie. 64-to-34.

**Comment by chris-langfield** [comment]
Per dev meeting we can merge this code as-is because it does not change the actual result of downsampling. Centerpoint energy loss discrepancy can break out into an issue

**Review by janden — APPROVED** [review]

**Pull request merged**
