### PR TITLE
Add an example contributors table in markdown

### LINKED ISSUE #136: Build a developer list
There is no unique place to list the names of all developers although there is a couple of places mentioning this. A separate file might be necessary.

### PR DESCRIPTION
**Pull request by garrettwrong**
Resolves #136 .

This is just an (incomplete) example.  It is open for discussion.  If it is acceptable, lets try to collect any missing contacts or details, and I can add.

One thing to note is that emails in a file on a public repo would be crawl-able.  Maybe we would not want them committed.. (though most of this info is within the git logs already..).

### CODE REVIEW

**Comment by garrettwrong** [comment]
For reference, the parsed file as served by Github:

https://github.com/garrettwrong/ASPIRE-Python/blob/example_contributors_md/CONTRIBUTORS.md

**Comment by junchaoxia** [comment]
I think it looks good. Ayelet Heimowitz (ayeleth@princeton.edu) should be in the list too. The years information for Vineet and I are not accurate. Probably it is not necessary to keep this column. Another column can be added is what is the major work (submodule of ASPIRE).

**Comment by garrettwrong** [comment]
Cool, I'll wait for any other people to chime in before making changes.  Years were just a guess. If it isn't helpful I can rm.

I was thinking we could use the "Focus" column for what you suggest, but didn't really complete it well. Being rather new, I'm not confident enough to say what other people focused on yet, so I just put in a role if it was obvious.

Thanks for taking a look.

**Comment by janden** [comment]
Looks reasonable. For e-mails, let's use the e-mails that are in the commits (if they correspond to actual e-mail addresses) and if people want to modify it, that's fine. I don't know if we need the focus and years column. We also need add Ayelet, as Junchao says. 

Then there's the question of the MATLAB code. There have been quite a few contributors there (Jane Zhao, Lanhui Wang, and others). Do these get added as “contributors” to the Python code?

**Comment by garrettwrong** [comment]
I removed the focus and year columns.  I did not see Ayelet in this repo, but when I went searching for her github handle she had activity in the PU one, interesting, added.

I don't really know how to address the MATLAB contributors other than to say they shouldn't be left out if we're porting their code.  If we think of no other way, I can always add Focus back in (maybe with a different name), and indicate they contributed to that effort.

**Comment by janden** [comment]
> I did not see Ayelet in this repo, but when I went searching for her github handle she had activity in the PU one, interesting, added.

So most of her work has been here: https://github.com/PrincetonUniversity/APPLEpicker, which was ported into Python here: https://github.com/PrincetonUniversity/APPLEpicker-python, which was eventually integrated into the current repo.

> I don't really know how to address the MATLAB contributors other than to say they shouldn't be left out if we're porting their code. If we think of no other way, I can always add Focus back in (maybe with a different name), and indicate they contributed to that effort.

Would it be that bad to just add them as authors, plain and simple? If we want to make it clear that their work was on a previous version, we can set up two tables: one for the MATLAB version and one for the (current) Python version.

**Comment by garrettwrong** [comment]
I changed to ReStructuredText so the same file can be used natively in the official (sphinx) docs.

Also add Mor Cohen.  @janden , would you know if Bruno Luong was part of the ASPIRE_MATLAB development effort, or if we just use his MinMax code..?   

There were a couple other names in the MATLAB code, but checking their cv it seems we are just citing using their code, not contributing directly to ASPIRE.

I think if we don't know someone immediately missing, we can undraft this and just add them later.

**Comment by garrettwrong** [comment]
New rst parsed in github like this:
https://github.com/garrettwrong/ASPIRE-Python/blob/example_contributors_md/CONTRIBUTORS.rst

And in the docs:
AuthorsRST

**Comment by garrettwrong** [comment]
I just realized I missed Joakim's comment.  Will add, Jane Zhao, Lanhui Wang, few minutes.

**Review by junchaoxia — COMMENTED** [review]
It might be better to separate the contributors in two tables as Joakim suggested. I believe there are more contributors for the Matlab version as listed. Amit might the better people for this.  Probably we should just create the list for the Python version first and notice that this only for Python version and more contributors for Matlab version.  The website lists team members of ASPIRE,   http://spr.math.princeton.edu/team.

**Comment by garrettwrong** [comment]
Yes I saw the team list, and I should add a link to that page.  Making two tables is easy.  Figuring out the content is apparently not.  What I assembled are the people listed in git, those with `Author` in MATLAB, and those mentioned by Joakim.  The nature of the code contributors list is usually for those who performed the programming, and I don't have an easy way to tell for the MATLAB code in hand, or based on the website.  I'm not convinced it corresponds 1:1 with the team list.  It would be silly to bring Amit in on a housekeeping task anytime soon. If nobody presently can confidently say x,y,z wrote the MATLAB code, then we can:

- have two tables, where the MATLAB table is simpler(and a WIP), bc we are missing all details...
- drop that MATLAB table idea for now
  - people brought to attention are later included in the single table. Simple to add.
- do nothing and wait until we can make it perfect. This  branch is unlikely to develop non trivial conflicts.
- Take the stance that all people on the website contributed.
  - then, we should just update the website with RSEs, link, and drop this PR/Issue.

I will make the two table version, push it, and you guys can take a look.  If it is better we more forward, worse roll it back.  We should be able to wrap this up quickly.

**Comment by garrettwrong** [comment]
Let me know if the two table setup is better. Thanks.

https://github.com/garrettwrong/ASPIRE-Python/blob/example_contributors_md/CONTRIBUTORS.rst

**Review by junchaoxia — APPROVED** [review]
It looks very good. I think we can add new things later if we forget something or somebody. Joakim's email probably need to be updated.

**Pull request merged**
